name: Unit Test

on: push

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run unit test
        run: make unit -C test/
